services:
  app:
    build: .
    command: bash -c "
        alembic upgrade head &&
        python main.py
      "
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: web_chat
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    expose:
      - 5532
    ports:
      - "5532:5532"
    command: -p 5532