"""delete resevier field

Revision ID: e7a560875609
Revises: 6212fa063c92
Create Date: 2023-11-17 13:51:13.760630

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e7a560875609"
down_revision: Union[str, None] = "6212fa063c92"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("messages_receiver_id_fkey", "messages", type_="foreignkey")
    op.drop_column("messages", "receiver_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "messages",
        sa.Column("receiver_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.create_foreign_key(
        "messages_receiver_id_fkey", "messages", "users", ["receiver_id"], ["id"]
    )
    # ### end Alembic commands ###
